name: teko_test_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

   
  #state management
  flutter_bloc: ^8.1.2

  #make request to api
  internet_connection_checker: ^1.0.0+1
  #network
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  dio: ^5.3.3
  # Misc
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  #Database
  floor: any

  #Data class
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  #service locator
  get_it: ^7.6.0
  injectable: ^2.3.2
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0 
  path_provider: ^2.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #code generators
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  build_runner: ^2.4.6

  retrofit_generator: ^8.0.1
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

